# Generated by Django 5.2.3 on 2025-06-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_api', '0003_message_author_alter_message_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
